-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingInPaise" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingWaived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "freeShippingThresholdSnapshotInPaise" INTEGER;
