/* ===================================================================
   E-Commerce Placeholder Data
   Mock products, categories, and gifts for the frontend shop
   =================================================================== */

import type { Product, ProductCategory } from "./ecom-types";

/* ── Categories ──────────────────────────────────────────────────── */

export const placeholderCategories: ProductCategory[] = [
  {
    id: "cat-1",
    name: "Return Gifts",
    slug: "return-gifts",
    icon: "Gift",
    description: "Thoughtful gifts your little guests will love to take home",
    productCount: 8,
  },
  {
    id: "cat-2",
    name: "Activity Kits",
    slug: "activity-kits",
    icon: "Palette",
    description: "Fun DIY kits and creative activities for kids",
    productCount: 4,
  },
  {
    id: "cat-3",
    name: "Personalized Items",
    slug: "personalized-items",
    icon: "Sparkles",
    description: "Custom-made keepsakes with your child's name",
    productCount: 4,
  },
  {
    id: "cat-4",
    name: "Stationery",
    slug: "stationery",
    icon: "PenTool",
    description: "Themed pencils, erasers, notebooks and more",
    productCount: 4,
  },
];

/* ── Products ────────────────────────────────────────────────────── */

export const placeholderProducts: Product[] = [
  // ═══ RETURN GIFTS ═══
  {
    id: "prod-1",
    title: "Space Explorer Sipper Bottle",
    slug: "space-explorer-sipper-bottle",
    sku: "VBC-RG-001",
    price: 249,
    compareAtPrice: 349,
    description: "A galaxy-themed insulated sipper bottle perfect for little astronauts. Features glow-in-the-dark stars and a leak-proof lid. Made from BPA-free food-grade material, this 400ml bottle is ideal for school and outings. Each bottle can be personalized with the child's name.",
    shortDescription: "Galaxy-themed insulated sipper with glow-in-the-dark stars",
    images: ["/theme/space_theme.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-1",
    themeTags: ["space-theme"],
    categoryTags: ["return-gifts"],
    stock: 45,
    maxOrderQuantity: 20,
    lowStockThreshold: 10,
    isActive: true,
    personalizationFields: [
      { id: "pf-1", label: "Child's Name", type: "text", required: false, placeholder: "e.g. Aarav", maxLength: 20 },
    ],
    createdAt: "2026-06-01",
  },
  {
    id: "prod-2",
    title: "Cocomelon Fun Lunch Box",
    slug: "cocomelon-fun-lunch-box",
    sku: "VBC-RG-002",
    price: 199,
    description: "A colorful Cocomelon-themed lunch box with compartments for snacks and a main meal. Features the beloved JJ character and is microwave-safe. Comes with a matching spoon and fork set.",
    shortDescription: "Colorful Cocomelon lunch box with compartments & cutlery set",
    images: ["/theme/cocomelon_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-1",
    themeTags: ["cocomelon-theme"],
    categoryTags: ["return-gifts"],
    stock: 32,
    maxOrderQuantity: 15,
    lowStockThreshold: 8,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-05",
  },
  {
    id: "prod-3",
    title: "Princess Tiara Gift Set",
    slug: "princess-tiara-gift-set",
    sku: "VBC-RG-003",
    price: 349,
    compareAtPrice: 449,
    description: "A magical princess gift set including a sparkling tiara, a wand, and a mini jewelry box. Each piece is adorned with pink and purple gems. Perfect for making every little princess feel extra special at the party.",
    shortDescription: "Sparkling tiara, wand & mini jewelry box gift set",
    images: ["/theme/princess_theme.png", "/theme/gallery_setup.png"],
    categoryId: "cat-1",
    themeTags: ["princess-theme"],
    categoryTags: ["return-gifts"],
    stock: 5,
    maxOrderQuantity: 10,
    lowStockThreshold: 8,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-10",
  },
  {
    id: "prod-4",
    title: "Jungle Safari Animal Figurine Set",
    slug: "jungle-safari-animal-figurine-set",
    sku: "VBC-RG-004",
    price: 299,
    description: "A collectible set of 6 hand-painted jungle animal figurines including a lion, elephant, giraffe, zebra, monkey, and parrot. Made from non-toxic, child-safe resin. Comes in a themed gift box shaped like a treasure chest.",
    shortDescription: "Set of 6 hand-painted jungle animal figurines in gift box",
    images: ["/theme/jungle_safari_theme.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-1",
    themeTags: ["jungle-safari-theme"],
    categoryTags: ["return-gifts"],
    stock: 18,
    maxOrderQuantity: 15,
    lowStockThreshold: 5,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-12",
  },
  {
    id: "prod-5",
    title: "Glow Star Night Light",
    slug: "glow-star-night-light",
    sku: "VBC-RG-005",
    price: 179,
    description: "A cute star-shaped LED night light that projects a gentle galaxy pattern on the ceiling. USB rechargeable with 3 color modes. Comes in a gift-ready box. Battery lasts up to 8 hours on a single charge.",
    shortDescription: "Star-shaped LED night light with galaxy projection",
    images: ["/theme/space_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-1",
    themeTags: ["space-theme", "princess-theme"],
    categoryTags: ["return-gifts"],
    stock: 0,
    maxOrderQuantity: 10,
    lowStockThreshold: 5,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-15",
  },
  {
    id: "prod-6",
    title: "Rainbow Bubble Wand Set",
    slug: "rainbow-bubble-wand-set",
    sku: "VBC-RG-006",
    price: 129,
    description: "A set of 3 oversized bubble wands in rainbow colors. Each wand creates giant bubbles that shimmer in sunlight. Non-toxic bubble solution included. Great for outdoor celebrations!",
    shortDescription: "Set of 3 oversized rainbow bubble wands with solution",
    images: ["/theme/gallery_setup.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-1",
    themeTags: ["cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["return-gifts"],
    stock: 60,
    maxOrderQuantity: 25,
    lowStockThreshold: 15,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-18",
  },
  {
    id: "prod-7",
    title: "Themed Goodie Bag Bundle",
    slug: "themed-goodie-bag-bundle",
    sku: "VBC-RG-007",
    price: 149,
    description: "A pre-packed goodie bag filled with themed treats: 2 candy packs, a sticker sheet, a mini toy, a temporary tattoo, and a thank-you card. Available in all celebration themes. Minimum order of 5 bags.",
    shortDescription: "Pre-packed goodie bag with candies, toys & stickers",
    images: ["/theme/gallery_cake.png", "/theme/gallery_setup.png"],
    categoryId: "cat-1",
    themeTags: ["space-theme", "cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["return-gifts"],
    stock: 100,
    maxOrderQuantity: 50,
    lowStockThreshold: 20,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-20",
  },
  {
    id: "prod-8",
    title: "Mini Telescope Gift",
    slug: "mini-telescope-gift",
    sku: "VBC-RG-008",
    price: 399,
    description: "A real working mini telescope for budding astronomers! 20x magnification, compact design perfect for little hands. Comes with a simple star chart and a carrying pouch. An educational and memorable return gift.",
    shortDescription: "Working mini telescope with star chart & carrying pouch",
    images: ["/theme/space_theme.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-1",
    themeTags: ["space-theme"],
    categoryTags: ["return-gifts"],
    stock: 12,
    maxOrderQuantity: 10,
    lowStockThreshold: 5,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-22",
  },

  // ═══ ACTIVITY KITS ═══
  {
    id: "prod-9",
    title: "Space Rocket DIY Craft Kit",
    slug: "space-rocket-diy-craft-kit",
    sku: "VBC-AK-001",
    price: 349,
    description: "Build your own rocket! This DIY craft kit includes pre-cut foam pieces, stickers, paints, and step-by-step instructions. Kids can assemble and paint their own rocket ship. Ages 4+. Keeps kids engaged for 30-45 minutes.",
    shortDescription: "Build-your-own rocket craft kit with paints & stickers",
    images: ["/theme/space_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-2",
    themeTags: ["space-theme"],
    categoryTags: ["activity-kits"],
    stock: 25,
    maxOrderQuantity: 15,
    lowStockThreshold: 8,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-25",
  },
  {
    id: "prod-10",
    title: "Jungle Safari Mask Making Kit",
    slug: "jungle-safari-mask-making-kit",
    sku: "VBC-AK-002",
    price: 279,
    description: "Create your own jungle animal masks! Kit includes 6 pre-printed mask templates (lion, tiger, monkey, parrot, elephant, giraffe), elastic bands, crayons, and glitter. Perfect group activity for parties.",
    shortDescription: "Make 6 jungle animal masks with crayons & glitter",
    images: ["/theme/jungle_safari_theme.png", "/theme/gallery_setup.png"],
    categoryId: "cat-2",
    themeTags: ["jungle-safari-theme"],
    categoryTags: ["activity-kits"],
    stock: 30,
    maxOrderQuantity: 20,
    lowStockThreshold: 10,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-06-28",
  },
  {
    id: "prod-11",
    title: "Princess Crown Decorating Kit",
    slug: "princess-crown-decorating-kit",
    sku: "VBC-AK-003",
    price: 299,
    description: "Decorate your own princess crown! Each kit contains a plain foam crown, adhesive gems, sequins, glitter glue, ribbon, and stickers. Every guest makes their own unique crown to wear and take home.",
    shortDescription: "Decorate-your-own princess crown with gems & glitter",
    images: ["/theme/princess_theme.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-2",
    themeTags: ["princess-theme"],
    categoryTags: ["activity-kits"],
    stock: 22,
    maxOrderQuantity: 15,
    lowStockThreshold: 8,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-01",
  },
  {
    id: "prod-12",
    title: "Cocomelon Coloring Activity Pack",
    slug: "cocomelon-coloring-activity-pack",
    sku: "VBC-AK-004",
    price: 199,
    description: "A Cocomelon-themed activity pack with a coloring book (20 pages), a set of 12 crayons, 3 sticker sheets, and a connect-the-dots puzzle book. Keeps little ones happily engaged during the party.",
    shortDescription: "Cocomelon coloring book, crayons, stickers & puzzles",
    images: ["/theme/cocomelon_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-2",
    themeTags: ["cocomelon-theme"],
    categoryTags: ["activity-kits"],
    stock: 40,
    maxOrderQuantity: 20,
    lowStockThreshold: 10,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-03",
  },

  // ═══ PERSONALIZED ITEMS ═══
  {
    id: "prod-13",
    title: "Custom Name Sipper Bottle",
    slug: "custom-name-sipper-bottle",
    sku: "VBC-PI-001",
    price: 349,
    compareAtPrice: 449,
    description: "A premium stainless-steel sipper bottle personalized with your child's name in beautiful calligraphy. Available in 4 colors: Galaxy Blue, Princess Pink, Jungle Green, Cocomelon Red. 500ml capacity, double-wall insulated.",
    shortDescription: "Stainless steel sipper with personalized calligraphy name",
    images: ["/theme/gallery_setup.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-3",
    themeTags: ["space-theme", "cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["personalized-items"],
    stock: 35,
    maxOrderQuantity: 20,
    lowStockThreshold: 10,
    isActive: true,
    personalizationFields: [
      { id: "pf-2", label: "Child's Name", type: "text", required: true, placeholder: "e.g. Aarav", maxLength: 15 },
      { id: "pf-3", label: "Age", type: "number", required: false, placeholder: "e.g. 5" },
    ],
    createdAt: "2026-07-05",
  },
  {
    id: "prod-14",
    title: "Personalized Story Book",
    slug: "personalized-story-book",
    sku: "VBC-PI-002",
    price: 499,
    description: "A custom illustrated storybook where your child is the hero! Choose from Space Adventure, Jungle Quest, Princess Magic, or Cocomelon Fun. The child's name and age are woven into the story and illustrations. 24 pages, hardcover.",
    shortDescription: "Custom storybook with your child as the hero",
    images: ["/theme/gallery_cake.png", "/theme/gallery_setup.png"],
    categoryId: "cat-3",
    themeTags: ["space-theme", "cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["personalized-items"],
    stock: 15,
    maxOrderQuantity: 5,
    lowStockThreshold: 5,
    isActive: true,
    personalizationFields: [
      { id: "pf-4", label: "Child's Name", type: "text", required: true, placeholder: "e.g. Priya", maxLength: 15 },
      { id: "pf-5", label: "Age", type: "number", required: true, placeholder: "e.g. 4" },
    ],
    createdAt: "2026-07-08",
  },
  {
    id: "prod-15",
    title: "Custom Photo Frame with Name",
    slug: "custom-photo-frame-with-name",
    sku: "VBC-PI-003",
    price: 279,
    description: "A beautiful wooden photo frame with the birthday child's name laser-engraved. Available in themed designs: rockets & planets, watermelons & JJ, tiaras & castles, or leaves & animals. Fits a 6×4 inch photo.",
    shortDescription: "Laser-engraved wooden frame with themed design",
    images: ["/theme/gallery_balloons.png", "/theme/gallery_cake.png"],
    categoryId: "cat-3",
    themeTags: ["space-theme", "cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["personalized-items"],
    stock: 28,
    maxOrderQuantity: 15,
    lowStockThreshold: 8,
    isActive: true,
    personalizationFields: [
      { id: "pf-6", label: "Child's Name", type: "text", required: true, placeholder: "e.g. Ishaan", maxLength: 15 },
    ],
    createdAt: "2026-07-10",
  },
  {
    id: "prod-16",
    title: "Name-Printed Party Caps (Set of 10)",
    slug: "name-printed-party-caps",
    sku: "VBC-PI-004",
    price: 199,
    description: "A set of 10 party caps printed with the birthday child's name and age. Choose a theme — each set has a matching themed design. Elastic chin straps included. Great for group photos!",
    shortDescription: "Set of 10 themed party caps with custom name printing",
    images: ["/theme/gallery_setup.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-3",
    themeTags: ["space-theme", "cocomelon-theme", "princess-theme", "jungle-safari-theme"],
    categoryTags: ["personalized-items"],
    stock: 50,
    maxOrderQuantity: 10,
    lowStockThreshold: 15,
    isActive: true,
    personalizationFields: [
      { id: "pf-7", label: "Birthday Child's Name", type: "text", required: true, placeholder: "e.g. Riya", maxLength: 15 },
      { id: "pf-8", label: "Age", type: "number", required: true, placeholder: "e.g. 6" },
    ],
    createdAt: "2026-07-12",
  },

  // ═══ STATIONERY ═══
  {
    id: "prod-17",
    title: "Space Theme Stationery Box",
    slug: "space-theme-stationery-box",
    sku: "VBC-ST-001",
    price: 159,
    description: "A cosmic stationery set in a rocket-shaped pencil box. Includes 2 pencils, an eraser, a sharpener, a ruler, and a mini notebook — all with space-themed designs. Perfect return gift for school-going kids.",
    shortDescription: "Rocket pencil box with space-themed stationery set",
    images: ["/theme/space_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-4",
    themeTags: ["space-theme"],
    categoryTags: ["stationery"],
    stock: 55,
    maxOrderQuantity: 25,
    lowStockThreshold: 15,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-14",
  },
  {
    id: "prod-18",
    title: "Jungle Adventure Notebook Set",
    slug: "jungle-adventure-notebook-set",
    sku: "VBC-ST-002",
    price: 129,
    description: "A set of 3 mini notebooks (A6 size) with jungle animal covers — lion, elephant, and giraffe. 40 ruled pages each, perfect for doodling and writing. Comes bundled with a jungle-print pencil.",
    shortDescription: "3 mini jungle notebooks with animal covers & pencil",
    images: ["/theme/jungle_safari_theme.png", "/theme/gallery_setup.png"],
    categoryId: "cat-4",
    themeTags: ["jungle-safari-theme"],
    categoryTags: ["stationery"],
    stock: 42,
    maxOrderQuantity: 20,
    lowStockThreshold: 12,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-16",
  },
  {
    id: "prod-19",
    title: "Princess Diary & Pen Set",
    slug: "princess-diary-pen-set",
    sku: "VBC-ST-003",
    price: 189,
    description: "A glittery princess diary with a lock and key, paired with a fluffy feather pen. The diary has 60 pages with princess-themed borders. A magical keepsake every little girl will treasure.",
    shortDescription: "Glittery princess diary with lock & feather pen",
    images: ["/theme/princess_theme.png", "/theme/gallery_balloons.png"],
    categoryId: "cat-4",
    themeTags: ["princess-theme"],
    categoryTags: ["stationery"],
    stock: 20,
    maxOrderQuantity: 15,
    lowStockThreshold: 5,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-18",
  },
  {
    id: "prod-20",
    title: "Cocomelon Crayon & Stamp Set",
    slug: "cocomelon-crayon-stamp-set",
    sku: "VBC-ST-004",
    price: 149,
    description: "A fun Cocomelon-branded set of 12 washable crayons and 6 themed stamps (JJ, TomTom, YoYo, watermelon, school bus, puppy). Non-toxic, safe for ages 3+. Comes in a reusable zippered pouch.",
    shortDescription: "12 washable crayons & 6 Cocomelon character stamps",
    images: ["/theme/cocomelon_theme.png", "/theme/gallery_cake.png"],
    categoryId: "cat-4",
    themeTags: ["cocomelon-theme"],
    categoryTags: ["stationery"],
    stock: 38,
    maxOrderQuantity: 20,
    lowStockThreshold: 10,
    isActive: true,
    personalizationFields: [],
    createdAt: "2026-07-20",
  },
];

/* ── Helper: get products by theme ───────────────────────────────── */
export function getProductsByTheme(themeSlug: string): Product[] {
  return placeholderProducts.filter((p) => p.themeTags.includes(themeSlug) && p.isActive);
}

/* ── Helper: get products by category ────────────────────────────── */
export function getProductsByCategory(categorySlug: string): Product[] {
  return placeholderProducts.filter((p) => p.categoryTags.includes(categorySlug) && p.isActive);
}

/* ── Helper: get product by slug ─────────────────────────────────── */
export function getProductBySlug(slug: string): Product | undefined {
  return placeholderProducts.find((p) => p.slug === slug);
}
